namespace Andes_EPC.Models
{
    public class ColumnName
    {
        public string lmk_key;
        public string address1;
        public string address2;
        public string address3;
        public string postcode;
        public string building_reference_number;
        public string current_energy_rating;
        public string current_energy_efficiency;
        public string potential_energy_efficiency;
        public string property_type;
        public string built_form;
        public string inspection_date;
        public string local_authority;
        public string constituency;
        public string county;
        public string lodgement_date;
        public string transaction_type;
        public string environment_impact_current;
        public string environment_impact_potential;
        public string energy_consumption_current;
        public string energy_consumption_potential;
        public string co2_emissions_current;
        public string co2_emiss_curr_per_floor_area;
        public string co2_emissions_potential;
        public string lighting_cost_current;
        public string lighting_cost_potential;
        public string heating_cost_current;
        public string heating_cost_potential;
        public string hot_water_cost_current;
        public string hot_water_cost_potential;
        public string total_floor_area;
        public string energy_tariff;
        public string mains_gas_flag;
        public string floor_level;
        public string flat_top_storey;
        public string flat_storey_count;
        public string main_heating_controls;
        public string multi_glaze_proportion;
        public string glazed_type;
        public string glazed_area;
        public string extension_count;
        public string number_habitable_rooms;
        public string number_heated_rooms;
        public string low_energy_lighting;
        public string number_open_fireplaces;
        public string hotwater_description;
        public string hot_water_energy_eff;
        public string hot_water_env_eff;
        public string floor_description;
        public string floor_energy_eff;
        public string floor_env_eff;
        public string windows_description;
        public string windows_energy_eff;
        public string windows_env_eff;
        public string walls_description;
        public string walls_energy_eff;
        public string walls_env_eff;
        public string secondheat_description;
        public string sheating_energy_eff;
        public string sheating_env_eff;
        public string roof_description;
        public string roof_energy_eff;
        public string roof_env_eff;
        public string mainheat_description;
        public string mainheat_energy_eff;
        public string mainheat_env_eff;
        public string mainheatcont_description;
        public string mainheatc_energy_eff;
        public string mainheatc_env_eff;
        public string lighting_description;
        public string lighting_energy_eff;
        public string lighting_env_eff;
        public string main_fuel;
        public string wind_turbine_count;
        public string heat_loss_corridoor;
        public string unheated_corridor_length;
        public string floor_height;
        public string photo_supply;
        public string solar_water_heating_flag;
        public string mechanical_ventilation;
        public string address;
        public string local_authority_label;
        public string constituency_label;
        public string certificate_hash;
 
    }
    /*
        column-names: [
        lmk-key;
        address1;
        address2;
        address3;
        postcode;
        building-reference-number;
        current-energy-rating;
        potential-energy-rating;
        current-energy-efficiency;
        potential-energy-efficiency;
        property-type;
        built-form;
        inspection-date;
        local-authority;
        constituency;
        county;
        lodgement-date;
        transaction-type;
        environment-impact-current;
        environment-impact-potential;
        energy-consumption-current;
        energy-consumption-potential;
        co2-emissions-current;
        co2-emiss-curr-per-floor-area;
        co2-emissions-potential;
        lighting-cost-current;
        lighting-cost-potential;
        heating-cost-current;
        heating-cost-potential;
        hot-water-cost-current;
        hot-water-cost-potential;
        total-floor-area;
        energy-tariff;
        mains-gas-flag;
        floor-level;
        flat-top-storey;
        flat-storey-count;
        main-heating-controls;
        multi-glaze-proportion;
        glazed-type;
        glazed-area;
        extension-count;
        number-habitable-rooms;
        number-heated-rooms;
        low-energy-lighting;
        number-open-fireplaces;
        hotwater-description;
        hot-water-energy-eff;
        hot-water-env-eff;
        floor-description;
        floor-energy-eff;
        floor-env-eff;
        windows-description;
        windows-energy-eff;
        windows-env-eff;
        walls-description;
        walls-energy-eff;
        walls-env-eff;
        secondheat-description;
        sheating-energy-eff;
        sheating-env-eff;
        roof-description;
        roof-energy-eff;
        roof-env-eff;
        mainheat-description;
        mainheat-energy-eff;
        mainheat-env-eff;
        mainheatcont-description;
        mainheatc-energy-eff;
        mainheatc-env-eff;
        lighting-description;
        lighting-energy-eff;
        lighting-env-eff;
        main-fuel;
        wind-turbine-count;
        heat-loss-corridoor;
        unheated-corridor-length;
        floor-height;
        photo-supply;
        solar-water-heating-flag;
        mechanical-ventilation;
        address;
        local-authority-label;
        constituency-label;
        certificate-hash
        ]*/
}